/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockOpnameRouteImport } from './routes/stock-opname'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerDisplayRouteImport } from './routes/customer-display'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminStockOpnameRouteImport } from './routes/admin.stock-opname'
import { Route as AdminSalesMarginRouteImport } from './routes/admin.sales-margin'
import { Route as AdminPriceCardsRouteImport } from './routes/admin.price-cards'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminItemsRouteImport } from './routes/admin.items'

const StockOpnameRoute = StockOpnameRouteImport.update({
  id: '/stock-opname',
  path: '/stock-opname',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDisplayRoute = CustomerDisplayRouteImport.update({
  id: '/customer-display',
  path: '/customer-display',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockOpnameRoute = AdminStockOpnameRouteImport.update({
  id: '/admin/stock-opname',
  path: '/admin/stock-opname',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesMarginRoute = AdminSalesMarginRouteImport.update({
  id: '/admin/sales-margin',
  path: '/admin/sales-margin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPriceCardsRoute = AdminPriceCardsRouteImport.update({
  id: '/admin/price-cards',
  path: '/admin/price-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/admin/items',
  path: '/admin/items',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/stock-opname': typeof StockOpnameRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/price-cards': typeof AdminPriceCardsRoute
  '/admin/sales-margin': typeof AdminSalesMarginRoute
  '/admin/stock-opname': typeof AdminStockOpnameRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/stock-opname': typeof StockOpnameRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/price-cards': typeof AdminPriceCardsRoute
  '/admin/sales-margin': typeof AdminSalesMarginRoute
  '/admin/stock-opname': typeof AdminStockOpnameRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/stock-opname': typeof StockOpnameRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/price-cards': typeof AdminPriceCardsRoute
  '/admin/sales-margin': typeof AdminSalesMarginRoute
  '/admin/stock-opname': typeof AdminStockOpnameRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer-display'
    | '/login'
    | '/pos'
    | '/stock-opname'
    | '/admin/items'
    | '/admin/members'
    | '/admin/price-cards'
    | '/admin/sales-margin'
    | '/admin/stock-opname'
    | '/admin/transactions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer-display'
    | '/login'
    | '/pos'
    | '/stock-opname'
    | '/admin/items'
    | '/admin/members'
    | '/admin/price-cards'
    | '/admin/sales-margin'
    | '/admin/stock-opname'
    | '/admin/transactions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/customer-display'
    | '/login'
    | '/pos'
    | '/stock-opname'
    | '/admin/items'
    | '/admin/members'
    | '/admin/price-cards'
    | '/admin/sales-margin'
    | '/admin/stock-opname'
    | '/admin/transactions'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerDisplayRoute: typeof CustomerDisplayRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  StockOpnameRoute: typeof StockOpnameRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPriceCardsRoute: typeof AdminPriceCardsRoute
  AdminSalesMarginRoute: typeof AdminSalesMarginRoute
  AdminStockOpnameRoute: typeof AdminStockOpnameRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock-opname': {
      id: '/stock-opname'
      path: '/stock-opname'
      fullPath: '/stock-opname'
      preLoaderRoute: typeof StockOpnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-display': {
      id: '/customer-display'
      path: '/customer-display'
      fullPath: '/customer-display'
      preLoaderRoute: typeof CustomerDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock-opname': {
      id: '/admin/stock-opname'
      path: '/admin/stock-opname'
      fullPath: '/admin/stock-opname'
      preLoaderRoute: typeof AdminStockOpnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales-margin': {
      id: '/admin/sales-margin'
      path: '/admin/sales-margin'
      fullPath: '/admin/sales-margin'
      preLoaderRoute: typeof AdminSalesMarginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/price-cards': {
      id: '/admin/price-cards'
      path: '/admin/price-cards'
      fullPath: '/admin/price-cards'
      preLoaderRoute: typeof AdminPriceCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerDisplayRoute: CustomerDisplayRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  StockOpnameRoute: StockOpnameRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPriceCardsRoute: AdminPriceCardsRoute,
  AdminSalesMarginRoute: AdminSalesMarginRoute,
  AdminStockOpnameRoute: AdminStockOpnameRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
